[database]
dbname = "neondb"  # Currently this is Neon's default database
user = "neondb_owner"
password = "npg_sYbjTQg5GUn0"
host = "ep-plain-base-a5et2w5s-pooler.us-east-2.aws.neon.tech"
port = "5432"
sslmode = "require"  # Important for Neon

# Alternatively, you can include the full connection string
url = "postgresql://neondb_owner:npg_sYbjTQg5GUn0@ep-plain-base-a5et2w5s-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"